# Generated by Django 3.2.5 on 2021-11-27 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dane_podstacji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miasto', models.CharField(max_length=100)),
                ('adres', models.TextField()),
                ('opis', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='dane_pojazdu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numer_VIN', models.CharField(max_length=100, unique=True)),
                ('marka_pojazdu', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('silnik', models.CharField(max_length=100)),
                ('typ_skrzyni', models.CharField(max_length=100)),
                ('przebieg', models.IntegerField()),
                ('rodzaj', models.CharField(max_length=100)),
                ('kategoria_PJ', models.CharField(max_length=100)),
                ('numer_rejestracyjny', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(max_length=100)),
                ('podstacja', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='AmbulanceApp.dane_podstacji')),
            ],
        ),
        migrations.CreateModel(
            name='dane_wyjazdu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_wyjazdu', models.DateTimeField()),
                ('data_powrotu', models.DateTimeField()),
                ('notatka', models.TextField(blank=True)),
                ('pojazd', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='AmbulanceApp.dane_pojazdu')),
            ],
        ),
        migrations.CreateModel(
            name='historia_naprawy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_naprawy', models.DateTimeField()),
                ('przebieg', models.IntegerField()),
                ('opis_usterek', models.TextField()),
                ('kategoria', models.CharField(max_length=100)),
                ('pojazd', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='AmbulanceApp.dane_pojazdu')),
            ],
        ),
        migrations.CreateModel(
            name='zdjecie_wyjazd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.ImageField(upload_to='files/interventions')),
                ('wyjazd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AmbulanceApp.dane_wyjazdu')),
            ],
        ),
        migrations.CreateModel(
            name='zdjecie_naprawa_przed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.ImageField(upload_to='files/repair/before')),
                ('naprawa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AmbulanceApp.historia_naprawy')),
            ],
        ),
        migrations.CreateModel(
            name='zdjecie_naprawa_po',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.ImageField(upload_to='files/repair/after')),
                ('naprawa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AmbulanceApp.historia_naprawy')),
            ],
        ),
        migrations.CreateModel(
            name='historia_ubezpieczenia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_wykupu', models.DateTimeField()),
                ('przebieg', models.IntegerField()),
                ('rodzaj', models.CharField(max_length=100)),
                ('pojazd', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='AmbulanceApp.dane_pojazdu')),
            ],
        ),
        migrations.CreateModel(
            name='historia_przegladu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_przegladu', models.DateTimeField()),
                ('przebieg', models.IntegerField()),
                ('wynik', models.CharField(max_length=100)),
                ('opis_usterek', models.TextField(blank=True)),
                ('pojazd', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='AmbulanceApp.dane_pojazdu')),
            ],
        ),
        migrations.CreateModel(
            name='faktura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.FileField(upload_to='files/repair/invoice')),
                ('naprawa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AmbulanceApp.historia_naprawy')),
            ],
        ),
    ]
